language: ruby
script: "bundle exec rake"
notifications:
  email:
    - unixcharles@gmail.com

matrix:
  allow_failures:
    - rvm: rbx-18mode
    - rvm: rbx-19mode
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - rbx-18mode
  - rbx-19mode
  - jruby-19mode
  - jruby-18mode